from django.db import models
from django.test import TestCase
from django.utils.text import slugify

from .models import BigS, UnicodeSlugField


class SlugFieldTests(TestCase):

    def test_slugfield_max_length(self):
        """
        SlugField honors max_length.
        """
        bs = BigS.objects.create(s='slug' * 50)
        bs = BigS.objects.get(pk=bs.pk)
        self.assertEqual(bs.s, 'slug' * 50)

    def test_slugfield_unicode_max_length(self):
        """
        SlugField with allow_unicode=True honors max_length.
        """
        bs = UnicodeSlugField.objects.create(s='你好你好' * 50)
        bs = UnicodeSlugField.objects.get(pk=bs.pk)
        self.assertEqual(bs.s, '你好你好' * 50)

    def test_slugfield_validate_slugify(self):
        """
        Slugfield validates strings generated by slugify
        """
        bs = models.SlugField(allow_unicode=True)
        self.assertEqual(bs.clean(slugify('W̊ ㏂ İa', allow_unicode=True), None), 'w-am-ia')
